enable-magisk-update = true # set this to false if you do not want to receive up

# you can use rvmm-config-gen to generate a config

# [YouTube]
# build-mode = "both"
# version = "auto"
# uptodown-dlurl = "https://youtube.en.uptodown.com/android"

# [Music]
# build-mode = "both"
# version = "auto"
# uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"

[Music-RVX]
app-name = "Music"
build-mode = "both"
version = "latest"
patches-source = "inotia00/revanced-patches"
integrations-source = "anddea/revanced-integrations"
rv-brand = "RVX"
patches-version = "v4.8.0-dev.2"
integrations-version = "v4.8.0-dev.2"
# uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
# excluded-patches = ""
# included-patches = "'Custom branding icon YouTube Music' 'Custom branding name YouTube Music'"
arch = "both"

[YouTube-RVX]
app-name = "YouTube"
build-mode = "both"
version = "19.16.39"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
rv-brand = "RVX"
patches-version = "v4.8.0-dev.2"
integrations-version = "v4.8.0-dev.2"
# uptodown-dlurl = "https://youtube.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
# excluded-patches = "'Shorts overlay buttons'"
# included-patches = "'Custom branding icon YouTube' 'Custom branding name YouTube'"
